### ISSUE TITLE
Error no module tkinter

### ISSUE THREAD

**Issue by MrThePatcher** [Andreas-Menzel/TUMLiveDownloader#1]
I tried running your code on my Virtual machine with Ubuntu on it and first i needed to install PySimpleGui. I installed it with pip. Now it says there is no module tkinter. I tried fixing it by installing tkinter with `sudo apt install python3-tk` but that didn't help. Do you know what i can do?

**Comment by Andreas-Menzel** [comment]
Hi!
What version of Ubuntu and Python are you using?
I have just installed Ubuntu 22.04 on a virtual machine and executed the following commands to install the dependencies. This worked for me..

```
pip3 install selenium
pip3 install PySimpleGui
sudo apt install python3-tk

python3 TUMLiveDownloader.py
```

**Comment by MrThePatcher** [comment]
Hi,
I use Ubuntu 20.04.5 and python 3.10.8

**Comment by Andreas-Menzel** [comment]
That's strange. I have Ubuntu 20.04.1 and Python 3.10.6 running and it works..

I have just created a no-ui version of the script where PySimpleGui (and thus tkinter) are not needed. To add a lecture, have a look at the terminal.

[TUMLiveDownloader v1.1.0](https://github.com/Andreas-Menzel/TUMLiveDownloader/releases/tag/v1.1.0)

Hope this helps!

edit 11:56: fixed link

**Comment by MrThePatcher** [comment]
Thank you, i looked into my installation a bit more, i think i destroyed something in my ubuntu System so completely my fault. I still appreciate the help, thank you very much

**Comment by Andreas-Menzel** [comment]
No problem at all :) If you have any other questions don't hesitate to ask!
